version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /mnt/shared/workspace:/app/workspace  # 소스 코드 저장
      - /mnt/shared/logs:/app/logs  # 로그 저장
      - /mnt/shared/data:/app/data  # 데이터 저장
#      - /volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - rag_network

  minio:
    container_name: milvus-minio
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
#    volumes:
 #     - /volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001" --address ":9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - rag_network

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.9
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./milvus/milvus.yaml:/milvus/configs/milvus.yaml
  #    - /volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - rag_network
    
  rag:
    build: ./rag
    container_name: milvus-rag
    volumes:
      - ./rag:/rag
      - shared_tmp:/tmp
    environment:
      - MILVUS_HOST=milvus-standalone
      - MILVUS_PORT=19530
    depends_on:
      - standalone
    networks:
      - rag_network
    ports:
      - "9010:9010"  # FastCGI용 포트
      - "5000:5000"  # 필요하면 Flask 직접 접근용
    command: uwsgi --ini /rag/uwsgi.ini
  
  nginx:
    image: nginx:latest
    container_name: milvus-nginx
    volumes:
      - shared_tmp:/tmp 
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - rag
    networks:
      - rag_network

networks:
  rag_network:
    external: true

volumes:
  shared_tmp:
