version: '3.5'
services:  
  flask:
    build: .
    container_name: flask-container
    volumes:
      - shared_tmp:/tmp
    networks:
      - docker_network
    ports:
      - "9010:9010"   # FastCGI 포트
      - "5000:5000"    # Flask 직접 접근 포트 (필요시)
    command: uwsgi --ini /app/uwsgi.ini
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - shared_tmp:/tmp 
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
    external: false
volumes:
  shared_tmp: